version: "2"

services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
    php:
        image: bylexus/apache-php7
        ports:
            - "8080:80"
        links:
            - "db"
        volumes:
            - ./code:/var/www
    db:
        image: mysql:latest
        ports:
            - "4306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 1234
